@JWT_TOKEN_ADMIN = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnYW1lX2ZpbmRlciIsInN1YiI6ImVzZW1lbnRlbGxpQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY2NDM4NzIxMX0.KxhZJyQ2i0xJIZBqi6kvHvQApLCAALpbZzfDF2fxkYM

@url = http://localhost:8080/pickup

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "esementelli@gmail.com",
    "password": "P@ssw0rd!"
}

###
GET {{url}} HTTP/1.1
Authorization: Bearer {{JWT_TOKEN_ADMIN}}

###
GET {{url}}/game/3 HTTP/1.1
Authorization: Bearer {{JWT_TOKEN_ADMIN}}

###
GET {{url}}/location/1 HTTP/1.1
Authorization: Bearer {{JWT_TOKEN_ADMIN}}

###
GET {{url}}/user/1 HTTP/1.1
Authorization: Bearer {{JWT_TOKEN_ADMIN}}


###
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN_ADMIN}}

{
    "pickUpInfo": "Just a casual game of Football",
    "playDate": "2022-12-01",
    "locationId": 1,
    "gameId": 1,
    "userId": 1
}

###
PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN_ADMIN}}

{
    "pickUpId": 2,
    "pickUpInfo": "Just tacos",
    "playDate": "2022-12-01",
    "locationId": 1,
    "gameId": 1,
    "userId": 1
}

###
DELETE {{url}}/2 HTTP/1.1
Authorization: Bearer {{JWT_TOKEN_ADMIN}}
