@JWT_TOKEN_ADMIN = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnYW1lX2ZpbmRlciIsInN1YiI6ImVzZW1lbnRlbGxpQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY2NDM5Mjg2Nn0.qdvhQbUWFW6bhf6PS6MJpSZE6xPe7n6A_e7KDqzjGc0


@url = http://localhost:8080/user


### find By Id
GET {{url}} HTTP/1.1
Authorization: Bearer {{JWT_TOKEN_ADMIN}}

### Add
POST {{url}} HTTP/1/1
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN_ADMIN}}

{
    "username": "esementelli",
    "firstName": "james",
    "lastName": "sementelli",
    "email": "esementelli@gmail.com",
    "locationId": 2
}

###
PUT {{url}}/6 HTTP/1/1
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN_ADMIN}}

{
    "userId": 6,
    "username": "esementelli",
    "firstName": "john",
    "lastName": "sementelli",
    "email": "esementelli@gmail.com",
    "locationId": 2
}

### Delete
DELETE {{url}}/6 HTTP/1.1
Authorization: Bearer {{JWT_TOKEN_ADMIN}}