@JWT_TOKEN_ADMIN = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnYW1lX2ZpbmRlciIsInN1YiI6ImVzZW1lbnRlbGxpQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY2NDM4MDU0N30.bourUAHu-WwOv8JkSG8BcBso85z7EDsGsMLaKQuYc18
@url = http://localhost:8080/user

### find By Id
GET {{url}} HTTP/1.1
Authorization: Bearer {{JWT_TOKEN_ADMIN}}

### Add
POST {{url}} HTTP/1/1
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN_ADMIN}}

{
    "firstName": "james",
    "lastName": "sementelli",
    "username": "esementelli",
    "email": "esementelli@gmail.com"
}

###
PUT {{url}} HTTP/1/1
Content-Type: application/json

{
    "userId": 1,
    "firstName": "james",
    "lastName": "sementelli",
    "username": "esementelli",
    "email": "esementelli@gmail.com"
}


### Update
PUT {{url}}/15 HTTP/1.1
Content-Type: application/json

{
    "locationId": 15,
    "latitude": 33,
    "longitude": -99.9992
}

### Delete
DELETE {{url}}/2 HTTP/1.1